name: MagicMarker
favicon: null
layout_spectrum: 0.3490321491844952
typography_spectrum: 0.15496177575550973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8986801481805742
  lightness: 0.9974888516589999
  saturation: 0.8530936290044338
  rhythmicContrast: 0.457888521021232
purpose: []
